database: #TODO: Collect from AWS
  dbname: testDb
  username: postgres
  password: pwd
  host: local


mapbox:
  api-key: pk.eyJ1IjoibmtsZW5rIiwiYSI6ImNtMnhmYzdtZDA0dmoybHB4dmc4ajIwNjQifQ.6PP5QqJPsRMysjD1NK6fXA


aws:
  root-email: neilklenkaws@gmail.com
